homepage:
  section1:
    header: "Welcome to my house :) "
    sub_header: "Hi, I'm Tram Nguyen, keep scrolling to learn more about me
    and my little adventures"
    button: "Read more"
    image:
      src: "images/trampic/profilepic.jpg"
      alt: "profilepic"

  section2:
    header: "My Mastercard Internship"
    sub_header: "Summer in St. Louis"
    button: "Read more"
    image:
      src: "images/trampic/stlprideintern.jpg"
      alt: "stlprideintern"

  section3:
    header: "MaSSP Vietnam - Trại hè Toán và Khoa học"
    sub_header: "My remote involvement with MaSSP"
    button: "Read more"
    image:
      src: "images/trampic/massp.jpg"
      alt: "massp"

  section4:
    header: "Asian Pacific American Coalition"
    sub_header: "APAC at Stetson University"
    button: "Read more"
    image:
      src: "images/trampic/apac2018.jpg"
      alt: "apacbanquet"

  section5:
    header: "My Happy Moments"
    sub_header: ""
    articles:
      - header: "APAC"
        sub_header: "APAC at Multiculture Student Council Banquet 2017"
        image:
          src: "images/trampic/sqapac2017.jpg"
          link:
          alt: "apac2017"

      - header: "Facebook"
        sub_header: "Facebook at SF Pride 2017"
        image:
          src: "images/trampic/sqfb.jpg"
          link:
          alt: "fb"
      - header: "Vietnam"
        sub_header: "Hai Van Pass - Đèo Hải Vân"
        image:
          src: "images/trampic/vnhaivan1.jpg"
          link:
          alt: "fbpride"
      - header: "Bonner Program at Stetson University"
        sub_header: "Hunger and Homeless Issue Area 2016"
        image:
          src: "images/trampic/bonnerpoverty.jpg"
          link:
          alt: "bonnerpoverty"
      - header: "Grace Hopper Conference"
        sub_header: "Stetson students at GHC 2017"
        image:
          src: "images/trampic/ghc.jpg"
          link:
          alt: "ghc2017"
