homepage:
  section1:
    header: "Hi, I'm Tram Nguyen"
    sub_header: "   I'm currently a senior majoring in Mathematics and Economics at Stetson University, Florida. Growing up in Vietnam, a developing country, I did not know that 'coding' can be a career, not to mention what 'data science' is.

    \n
    I recently discovered my love for data science, or in my mind, the combination of economics and math with a touch of computer science. With the experience working at companies such as Facebook or Mastercard, I learned that data science is more an art than a science, and my dream is to be able to create tools and technologies to help people everywhere with this art. "
    button: "Read more"
    button_link:
    image:
      src: "images/trampic/profilepic.jpg"
      alt: "profilepic"

  section2:
    header: "My Mastercard Internship"
    sub_header: "Summer in St. Louis"
    button: "Read more"
    button_link:
    image:
      src: "images/trampic/stlprideintern.jpg"
      alt: "stlprideintern"

  section3:
    header: "MaSSP Vietnam"
    sub_header: "My remote involvement with MaSSP"
    button: "Read more"
    button_link:
    image:
      src: "images/trampic/massp.jpg"
      alt: "massp"

  section4:
    header: "Grace Hopper Conference 2017"
    sub_header: "My first time to an all women conference"
    button: "Read more"
    button_link:
    image:
      src: "images/trampic/ghc.jpg"
      alt: "ghc"

  section5:
    header: "What else I've been up to :) "
    sub_header: ""
    articles:
      - header: "Data Science"
        sub_header: "How I learned about Data Science, Big Data,..."
        image:
          src: "images/trampic/data.png"
          link:
          alt: "http://blog.kaggle.com/2017/11/16/introducing-data-science-for-good-events-on-kaggle/"
      - header: "My Facebook Internship"
        sub_header: "Live an learn in Sillicon Valley"
        image:
          src: "images/trampic/fb.jpg"
          link:
          alt: "fb"
      - header: "Bonner Program at Stetson University"
        sub_header: "Hunger and Homeless Issue Area 2016"
        image:
          src: "images/trampic/bonnerpoverty.jpg"
          link:
          alt: "bonnerpoverty"
      - header: "Asian Pacific American Coalition"
        sub_header: "APAC at Stetson University"
        image:
          src: "images/trampic/apac2018.jpg"
          link:
          alt: "apac2017"

      - header: "Vietnam 2017"
        sub_header: "Hai Van Pass - Đèo Hải Vân"
        image:
          src: "images/trampic/vnhaivan1.jpg"
          link:
          alt: "vnhaivan1"

  section6:
    header:
    sub_header:
